import Layoutwrapper from "@/components/layouts/Layoutwrapper";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "IGWA",
  description: "Generated by create next app",
};


import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={dmSans.variable}>
        <AppRouterCacheProvider>
          <Layoutwrapper>{children}</Layoutwrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
