import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Layoutwrapper from "@/components/layouts/Layoutwrapper";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "IGWA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={dmSans.variable}>
        <Layoutwrapper>{children}</Layoutwrapper>
      </body>
    </html>
  );
}
